name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bookshop-service:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: bookstore
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
        options: --health-cmd="nc -z 127.0.0.1 2181" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build & Install Bookshop-Service
        run: |
          cd bookshop-service
          mvn clean install 
          ls ~/.m2/repository/com/cloud/bookshop/*
          echo "Bookshop-Service JAR installed in ~/.m2/repository."

      - name: Upload Bookshop-Service JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookshop-service-jar
          path: ~/.m2/repository/com/cloud/bookshop/bookshop-service/

  bookshop-data:
    runs-on: ubuntu-latest
    needs: bookshop-service
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: bookstore
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
        options: --health-cmd="nc -z 127.0.0.1 2181" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uadmin -padmin -e "SHOW DATABASES;"

      - name: Verify Zookeeper Connection
        run: |
          nc -zv 127.0.0.1 2181
          echo "Zookeeper is up and running!"

      - name: Download Bookshop-Service JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: bookshop-service-jar
          path: ~/.m2/repository/com/cloud/bookshop/bookshop-service/

      - name: Build Bookshop-Data
        run: |
          cd bookshop-data
          mvn clean install -DskipTests
          echo "BookShop build completed. JAR should now be in ~/.m2/repository."

      - name: Upload Bookshop-Data JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-jar
          path: ~/.m2/repository/com/cloud/bookshop/bookshop-data/

  bookshop-admin:
    runs-on: ubuntu-latest
    needs:
      - bookshop-data
      - bookshop-service
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: bookstore
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
        options: --health-cmd="nc -z 127.0.0.1 2181" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Restore Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uadmin -padmin -e "SHOW DATABASES;"

      - name: Verify Zookeeper Connection
        run: |
          nc -zv 127.0.0.1 2181
          echo "Zookeeper is up and running!"

      - name: Download Bookshop-Service JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: bookshop-service-jar
          path: ~/.m2/repository/com/cloud/bookshop/bookshop-service/0.0.1-SNAPSHOT/

      - name: Download Data JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: data-jar
          path: ~/.m2/repository/com/cloud/bookshop/data/0.0.1-SNAPSHOT/

      - name: Build Bookshop-Admin
        run: |
          cd bookshop-admin
          mvn clean package -DskipTests
          echo "Bookshop-Admin built successfully using BookShop JAR from ~/.m2/repository."
